name: Release Charts

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  workflow_dispatch:
    inputs:
      target:
        description: "target chart to release"
        type: string
        default: ""
        required: false
      dryrun:
        description: "dry-run"
        type: boolean
        default: true
        required: false
      backport-branch:
        description: "Branch or leave empty for current CI branch"
        type: string
        default: ""
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BACKPORT_BRANCH: ${{ github.event.inputs.backport-branch || '' }}
      BACKPORT_DIR: 'backport'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout Backport branch
        uses: actions/checkout@v4
        if: github.event.inputs.backport-branch != ''
        with:
          ref: ${{ env.BACKPORT_BRANCH }}
          path: ${{ env.BACKPORT_DIR }}

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.13.1

      - name: Add Helm repos
        run: |
          helm repo add mongodb https://mongodb.github.io/helm-charts

      - name: Allow script
        run: |
          chmod +x ./.github/actions/releaser/cr.sh

      - name: Helm Chart Dependency Releaser
        uses: ./.github/actions/releaser
        if: github.event.inputs.target == ''
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          charts_repo_url: https://mongodb.github.io/helm-charts
          target: |
            atlas-operator-crds
            community-operator-crds
          dryrun: ${{ github.event.inputs.dryrun }}

      - name: Get latest charts from repo
        run: |
          helm repo update

      - name: Helm Chart Releaser
        uses: ./.github/actions/releaser
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CHARTS_DIR: ${{ github.event.inputs.backport-branch == '' && 'charts' || format('{0}/charts', env.BACKPORT_DIR) }}
          MARK_LATEST: ${{ github.event.inputs.backport-branch == '' && 'true' || 'false' }}
        with:
          charts_repo_url: https://mongodb.github.io/helm-charts
          target: ${{ github.event.inputs.target }}
          dryrun: ${{ github.event.inputs.dryrun }}
          charts_dir: ${{ env.CHARTS_DIR }}
          mark_latest: ${{ env.MARK_LATEST }}
